
service: phone-verification-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
   #Replace with your own environment variables
   # MONGO_URI: ${env:MONGO_URI}
   # JWT_SECRET: ${env:JWT_SECRET}
   # TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
   # TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
   # TWILIO_VERIFY_SERVICE_SID: ${env:TWILIO_VERIFY_SERVICE_SID}

functions:
  app:
    handler: lambda.handler
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
      - schedule:
          rate: rate(5 minutes)

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5000
